# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
df = pd.read_csv('cardekho_imputated.csv',index_col=[0])

In [4]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB

In [6]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [8]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [13]:
df.head(2)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82.0,5,550000

In [10]:
df.drop(columns=['car_name','brand'],axis=1,inplace=True)

In [12]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [14]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [16]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [19]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X['model']=le1.fit_transform(X['model'])

In [28]:
numerical_feature = X.select_dtypes(exclude='object').columns
car_feature=['seller_type','fuel_type','transmission_type']

In [29]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
num_trans=StandardScaler()
car_transfor=OneHotEncoder(drop='first')
preprocess = ColumnTransformer(
    [
        ('onehotencoder',car_transfor,car_feature),
        ('standersclr',num_trans,numerical_feature)
    ]
    
)

In [30]:
X=preprocess.fit_transform(X)

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.25,random_state=41)

In [36]:
from sklearn.linear_model import LinearRegression ,Ridge,Lasso
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [39]:
def Evel_predict(true,predict):
    r2_scor = r2_score(true,predict)
    mae= mean_absolute_error(true,predict)
    mse= mean_squared_error(true,predict)
    rmse = np.sqrt(mse)
    return r2_scor,mae,rmse

In [44]:
models={
    'linearRegression':LinearRegression(),
    'SVR':SVR(),
    'KNeighborsRegressor':KNeighborsRegressor(),
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'RandomForestRegressor':RandomForestRegressor(),
    'AdaBoostRegressor':AdaBoostRegressor()
    }
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    #Train/Test prediction
    Y_train_pred =model.predict(X_train)
    Y_test_pred = model.predict(X_test)

    
    r2_scortrain,maetrain,rmsetrain=Evel_predict(y_train,Y_train_pred)
    r2_scortest,maetest,rmsetest=Evel_predict(y_test,Y_test_pred)

    print(list(models.keys())[i])
    print('Train set prediction\n')
    print('r2_score:{:.4f}'.format(r2_scortrain))
    print('mean Absolute Error:{:.4f}'.format(maetrain))
    print('RootMeanSquaredError{:.4f}'.format(rmsetrain))

    print('-'*32)

    print('Test Set Prediction')
    print('r2_score:{:.4f}'.format(r2_scortest))
    print('mean Absolute Error:{:.4f}'.format(maetest))
    print('Root Mean Squared Error:{:.4f}'.format(rmsetest))

    print('='*32)
    print('\n')

linearRegression
Train set prediction

r2_score:0.6238
mean Absolute Error:262949.6943
RootMeanSquaredError540120.4840
--------------------------------
Test Set Prediction
r2_score:0.6430
mean Absolute Error:272150.8829
Root Mean Squared Error:557627.9898
================================


SVR
Train set prediction

r2_score:-0.0576
mean Absolute Error:396023.6800
RootMeanSquaredError905659.9886
--------------------------------
Test Set Prediction
r2_score:-0.0549
mean Absolute Error:413344.0344
Root Mean Squared Error:958500.1470
================================


KNeighborsRegressor
Train set prediction

r2_score:0.8778
mean Absolute Error:89974.1370
RootMeanSquaredError307831.5213
--------------------------------
Test Set Prediction
r2_score:0.8183
mean Absolute Error:117924.7210
Root Mean Squared Error:397751.5052
================================


DecisionTreeRegressor
Train set prediction

r2_score:0.9995
mean Absolute Error:4699.3808
RootMeanSquaredError19439.2455
--------------------------------
Test Set Prediction
r2_score:0.8462
mean Absolute Error:128949.6215
Root Mean Squared Error:366037.8343
================================


RandomForestRegressor
Train set prediction

r2_score:0.9785
mean Absolute Error:39478.8653
RootMeanSquaredError129101.4201
--------------------------------
Test Set Prediction
r2_score:0.8850
mean Absolute Error:104725.6215
Root Mean Squared Error:316408.9208
================================


AdaBoostRegressor
Train set prediction

r2_score:0.7254
mean Absolute Error:360666.8529
RootMeanSquaredError461515.3462
--------------------------------
Test Set Prediction
r2_score:0.6646
mean Absolute Error:375441.1604
Root Mean Squared Error:540434.5429
================================

criterion: Literal['squared_error', 'friedman_mse', 'absolute_error', 'poisson'] = "squared_error",
    splitter: Literal['best', 'random'] = "best",
    max_depth: Int | None = None,
    min_samples_split: float = 2,
    min_samples_leaf: float = 1,
    min_weight_fraction_leaf: Float = 0,
    max_features: float | Literal['auto', 'sqrt', 'log2'] | None = None,
    random_state: Int | RandomState | None = None,
    max_leaf_nodes: Int | None = None,
    min_impurity_decrease: Float = 0,

n_estimators: Int = 100,
    *,
    criterion: Literal['squared_error', 'absolute_error', 'friedman_mse', 'poisson'] = "squared_error",
    max_depth: Int | None = None,
    min_samples_split: float = 2,
    min_samples_leaf: float = 1,
    min_weight_fraction_leaf: Float = 0,
    max_features: float | Literal['sqrt', 'log2'] = 1,
    max_leaf_nodes: Int | None = None,
    min_impurity_decrease: Float = 0,
    bootstrap: bool = True,
    oob_score: bool = Fals

stimator: Any = None,
    *,
    n_estimators: Int = 50,
    learning_rate: Float = 1,
    loss: Literal['linear', 'square', 'exponential'] = "linear",
    random_state: Int | RandomState | None = None,
    base_estimator: Any = "deprecated"

In [47]:
parem_decision_tree={
    'criterion':['squared_error', 'friedman_mse', 'absolute_error'],
    'max_depth': [1,2,3,4,5,6,10],
    'min_samples_split': [0.1,0.2,0.3,1],
    'min_samples_leaf': [0.1,0.2,0.01,1],
    'max_features': [1,2,3,4,5,6]
}
parem_forest={ 
    'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'] ,
   'max_depth': [1,2,3,4,5,6],
    'min_samples_split': [0.1,0.2,0.3,1],
    'min_samples_leaf': [0.1,0.2,0.01,1],
    'max_features': [1,2,3,4,5,6]

}
paremadda={
    'n_estimators':[10,20,30,50,60,90,100],
    'learning_rate':[0.1,.2,.3,.5,1],
    'loss':['linear', 'square', 'exponential']
    
}

In [49]:
models2=[
    ('DecisionTreeRegressor',DecisionTreeRegressor(),parem_decision_tree),
    ('RandomForestRegressor',RandomForestRegressor(),parem_forest),
    ('AdaBoostRegressor', AdaBoostRegressor(),paremadda)
]

In [55]:
from sklearn.model_selection import RandomizedSearchCV
best_parem ={}
for name,model,parem in models2:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=parem,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1
                                )
    random.fit(X_train,y_train)
    best_parem[name]=random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits

In [59]:
for model_name in best_parem:
    print(f'________best parem{model_name}_________')
    print(best_parem[model_name])

________best paremDecisionTreeRegressor_________
{'min_samples_split': 0.1, 'min_samples_leaf': 0.01, 'max_features': 6, 'max_depth': 6, 'criterion': 'absolute_error'}
________best paremRandomForestRegressor_________
{'min_samples_split': 0.1, 'min_samples_leaf': 1, 'max_features': 4, 'max_depth': 6, 'criterion': 'friedman_mse'}
________best paremAdaBoostRegressor_________
{'n_estimators': 60, 'loss': 'exponential', 'learning_rate': 0.1}

In [65]:
models = {
    'DecisionTreeRegressor':DecisionTreeRegressor(min_samples_split= 0.1, min_samples_leaf=0.01, max_features= 6, max_depth= 6, criterion ='absolute_error'),
    'RandomForestRegressor':RandomForestRegressor(min_samples_split= 0.1, min_samples_leaf= 1, max_features= 4, max_depth= 6, criterion= 'friedman_mse'),
    'AdaBoostRegressor':AdaBoostRegressor(n_estimators= 60, loss= 'exponential', learning_rate= 0.1)
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    #Prediction for train ,train
    Y_train_pred = model.predict(X_train)
    Y_Test_pred =model.predict(X_test)
    
    r2_scortrain,maetrain,rmsetrain=Evel_predict(y_train,Y_train_pred)
    r2_scortest,maetest,rmsetest=Evel_predict(y_test,Y_test_pred)

    print(list(models.keys())[i])
    print('Train set prediction\n')
    print('r2_score:{:.4f}'.format(r2_scortrain))
    print('mean Absolute Error:{:.4f}'.format(maetrain))
    print('RootMeanSquaredError{:.4f}'.format(rmsetrain))

    print('-'*32)

    print('Test Set Prediction')
    print('r2_score:{:.4f}'.format(r2_scortest))
    print('mean Absolute Error:{:.4f}'.format(maetest))
    print('Root Mean Squared Error:{:.4f}'.format(rmsetest))

    print('='*32)
    print('\n')

DecisionTreeRegressor
Train set prediction

r2_score:0.5323
mean Absolute Error:218538.3392
RootMeanSquaredError602294.7988
--------------------------------
Test Set Prediction
r2_score:0.6646
mean Absolute Error:375441.1604
Root Mean Squared Error:540434.5429
================================


RandomForestRegressor
Train set prediction

r2_score:0.5955
mean Absolute Error:212160.1077
RootMeanSquaredError560122.3932
--------------------------------
Test Set Prediction
r2_score:0.6646
mean Absolute Error:375441.1604
Root Mean Squared Error:540434.5429
================================


AdaBoostRegressor
Train set prediction

r2_score:0.8380
mean Absolute Error:223908.8861
RootMeanSquaredError354494.3825
--------------------------------
Test Set Prediction
r2_score:0.6646
mean Absolute Error:375441.1604
Root Mean Squared Error:540434.5429
================================