In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Customer_Sentiment.csv')

In [3]:
df.head()

,customer_id,gender,age_group,region,product_category,purchase_channel,platform,customer_rating,review_text,sentiment,response_time_hours,issue_resolved,complaint_registered
0,1,male,60+,north,automobile,online,flipkart,1,very disappointed with the quality.,negative,46,yes,yes
1,2,other,46-60,central,books,online,swiggy instamart,5,fast delivery and great packaging.,positive,5,yes,no
2,3,female,36-45,east,sports,online,facebook marketplace,1,very disappointed with the quality.,negative,38,yes,yes
3,4,female,18-25,central,groceries,online,zepto,2,product stopped working after few days.,negative,16,yes,yes
4,5,female,18-25,east,electronics,online,croma,3,neutral about the quality.,neutral,15,yes,no

In [4]:
df.isnull().sum()

customer_id             0
gender                  0
age_group               0
region                  0
product_category        0
purchase_channel        0
platform                0
customer_rating         0
review_text             0
sentiment               0
response_time_hours     0
issue_resolved          0
complaint_registered    0
dtype: int64

In [5]:
import pandas as pd

mapping = {
    "18-25": 21,
    "26-35": 30,
    "36-45": 40,
    "46-60": 53,
    "60+": 65
}

df["age_group"] = df["age_group"].map(mapping)

In [6]:
df

,customer_id,gender,age_group,region,product_category,purchase_channel,platform,customer_rating,review_text,sentiment,response_time_hours,issue_resolved,complaint_registered
0,1,male,65,north,automobile,online,flipkart,1,very disappointed with the quality.,negative,46,yes,yes
1,2,other,53,central,books,online,swiggy instamart,5,fast delivery and great packaging.,positive,5,yes,no
2,3,female,40,east,sports,online,facebook marketplace,1,very disappointed with the quality.,negative,38,yes,yes
3,4,female,21,central,groceries,online,zepto,2,product stopped working after few days.,negative,16,yes,yes
4,5,female,21,east,electronics,online,croma,3,neutral about the quality.,neutral,15,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,female,40,south,beauty,online,lenskart,1,very disappointed with the quality.,negative,40,yes,yes
24996,24997,other,65,central,automobile,online,flipkart,5,"amazing experience, highly recommend!",positive,25,yes,no
24997,24998,male,21,south,beauty,online,ajio,4,fast delivery and great packaging.,positive,9,yes,no
24998,24999,female,30,central,automobile,online,snapdeal,5,great value for money.,positive,65,no,no
24999,25000,male,53,central,travel,online,lenskart,3,"product is okay, nothing special.",neutral,67,no,no

In [7]:
cat1 = [feature for feature in df.columns if df[feature].dtype=='O']
for i in cat1:
    print(i,df[i].unique(),'\n')

gender ['male' 'other' 'female']

region ['north' 'central' 'east' 'south' 'west']

product_category ['automobile' 'books' 'sports' 'groceries' 'electronics' 'travel'
 'fashion' 'home & kitchen' 'beauty']

purchase_channel ['online']

platform ['flipkart' 'swiggy instamart' 'facebook marketplace' 'zepto' 'croma'
 'amazon' 'shopclues' 'tata cliq' 'snapdeal' 'paytm mall' 'ajio' 'myntra'
 'nykaa' 'reliance digital' 'meesho' 'bigbasket' 'lenskart' 'jiomart'
 'others' 'boat']

review_text ['very disappointed with the quality.'
 'fast delivery and great packaging.'
 'product stopped working after few days.' 'neutral about the quality.'
 'amazing experience, highly recommend!' 'great value for money.'
 'excellent product! exceeded expectations.'
 'product is okay, nothing special.' 'not worth the price.'
 'customer service was unhelpful.' 'late delivery and poor packaging.'
 'average experience overall.' 'works fine but could be better.'
 'very satisfied with the quality.'
 'delivery was fine, product is decent.']

sentiment ['negative' 'positive' 'neutral']

issue_resolved ['yes' 'no']

complaint_registered ['yes' 'no']

In [8]:
print(cat1)

['gender', 'region', 'product_category', 'purchase_channel', 'platform', 'review_text', 'sentiment', 'issue_resolved', 'complaint_registered']

In [9]:
laberl = ['gender','region','sentiment','purchase_channel','issue_resolved','complaint_registered']
cat2 = [feature for feature in cat1 if feature not in laberl]

In [10]:
for i in laberl:
    print(i,df[i].unique(),'\n')

gender ['male' 'other' 'female']

region ['north' 'central' 'east' 'south' 'west']

sentiment ['negative' 'positive' 'neutral']

purchase_channel ['online']

issue_resolved ['yes' 'no']

complaint_registered ['yes' 'no']

In [11]:
df.head(2)

,customer_id,gender,age_group,region,product_category,purchase_channel,platform,customer_rating,review_text,sentiment,response_time_hours,issue_resolved,complaint_registered
0,1,male,65,north,automobile,online,flipkart,1,very disappointed with the quality.,negative,46,yes,yes
1,2,other,53,central,books,online,swiggy instamart,5,fast delivery and great packaging.,positive,5,yes,no

In [12]:
df.drop(columns=['customer_id','region','purchase_channel'],axis=1,inplace=True)

In [13]:
df.drop('review_text',axis=1,inplace=True)

In [14]:
df.head(3)

,gender,age_group,product_category,platform,customer_rating,sentiment,response_time_hours,issue_resolved,complaint_registered
0,male,65,automobile,flipkart,1,negative,46,yes,yes
1,other,53,books,swiggy instamart,5,positive,5,yes,no
2,female,40,sports,facebook marketplace,1,negative,38,yes,yes

In [15]:
df.isnull().sum()

gender                  0
age_group               0
product_category        0
platform                0
customer_rating         0
sentiment               0
response_time_hours     0
issue_resolved          0
complaint_registered    0
dtype: int64

In [16]:
cat1 = [feature for feature in df.columns if df[feature].dtype=='O']
for i in cat1:
    print(i,df[i].unique(),'\n')

gender ['male' 'other' 'female']

product_category ['automobile' 'books' 'sports' 'groceries' 'electronics' 'travel'
 'fashion' 'home & kitchen' 'beauty']

platform ['flipkart' 'swiggy instamart' 'facebook marketplace' 'zepto' 'croma'
 'amazon' 'shopclues' 'tata cliq' 'snapdeal' 'paytm mall' 'ajio' 'myntra'
 'nykaa' 'reliance digital' 'meesho' 'bigbasket' 'lenskart' 'jiomart'
 'others' 'boat']

sentiment ['negative' 'positive' 'neutral']

issue_resolved ['yes' 'no']

complaint_registered ['yes' 'no']

In [17]:
laberl = ['gender','sentiment','complaint_registered']
cat2 = [feature for feature in cat1 if feature not in laberl]

In [18]:
cat2

['product_category', 'platform', 'issue_resolved']

In [19]:
X= df.drop('issue_resolved',axis=1)
y=df['issue_resolved']

In [20]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
y=le1.fit_transform(y)

In [21]:
y = pd.DataFrame(y)

In [22]:
laberl

['gender', 'sentiment', 'complaint_registered']

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3= LabelEncoder()
le4=LabelEncoder()
le5=LabelEncoder()

In [25]:
X_train['gender']=le1.fit_transform(X_train['gender'])
X_train['sentiment']=le2.fit_transform(X_train['sentiment'])
X_train['complaint_registered']=le3.fit_transform(X_train['complaint_registered'])
X_train['product_category'] =le4.fit_transform(X_train['product_category'])
X_train['platform']=le5.fit_transform(X_train['platform'])

X_test['gender']=le1.transform(X_test['gender'])
X_test['sentiment']=le2.transform(X_test['sentiment'])
X_test['complaint_registered']=le3.transform(X_test['complaint_registered'])
X_test['product_category'] =le4.fit_transform(X_test['product_category'])
X_test['platform']=le5.fit_transform(X_test['platform'])

In [26]:
X_train

,gender,age_group,product_category,platform,customer_rating,sentiment,response_time_hours,complaint_registered
23311,0,21,8,0,5,2,60,0
23623,0,65,1,14,5,2,25,0
1020,1,65,2,0,1,0,70,1
12645,2,65,3,5,3,1,3,0
1533,1,53,0,8,2,0,25,1
...,...,...,...,...,...,...,...,...
21575,1,21,7,10,5,2,54,0
5390,1,65,3,6,4,2,12,0
860,2,40,5,15,3,1,19,0
15795,1,65,2,15,4,2,58,0
23654,2,21,3,13,4,2,39,0

In [28]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report,ConfusionMatrixDisplay, \
                            precision_score, recall_score, f1_score, roc_auc_score,roc_curve

In [30]:
def model_evel(true,predict):
    acc_sc = accuracy_score(true,predict)
    f1_scor = f1_score(true,predict)
    prec_scor = precision_score(true,predict)
    recall_sc = recall_score(true,predict)
    roc_scoe = roc_auc_score(true,predict)
    return acc_sc,f1_scor,prec_scor,recall_sc,roc_scoe

In [33]:
models ={
    'LogisticRegression':LogisticRegression(),
    'KNeighborsClassifier':KNeighborsClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'RandomforestClassifer':RandomForestClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier(),
    'XGclassifier':XGBClassifier()
    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    acc_sctrain,f1_scortrain,prec_scortrain,recall_sctyrain,roc_scoetrain=model_evel(y_train,y_train_pred)
    acc_sctest,f1_scortest,prec_scortest,recall_sctest,roc_scoetest=model_evel(y_test,y_test_pred)

    print(list(models.keys())[i])

    print('Training set pred')
    print('accuracy:{:.4f}'.format(acc_sctrain))
    print('f1score:{:.4f}'.format(f1_scortrain))
    print('precision:{:.4f}'.format(prec_scortrain))
    print('recall:{:.4f}'.format(recall_sctyrain))
    print('roc_auc:{:.4f}'.format(roc_scoetrain))
    print('-'*40)

    print('Test set prediction')
    print('accuracy:{:.4f}'.format(acc_sctest))
    print('f1score:{:.4f}'.format(f1_scortest))
    print('precision:{:.4f}'.format(prec_scortest))
    print('recall:{:.4f}'.format(recall_sctest))
    print('roc_auc:{:.4f}'.format(roc_scoetest))
    print('='*40)
    print('\n')

LogisticRegression
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================


KNeighborsClassifier
Training set pred
accuracy:0.9798
f1score:0.9848
precision:0.9837
recall:0.9859
roc_auc:0.9767
----------------------------------------
Test set prediction
accuracy:0.9630
f1score:0.9719
precision:0.9694
recall:0.9744
roc_auc:0.9578
========================================


DecisionTreeClassifier
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================


GradientBoostingClassifier
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================


RandomforestClassifer
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================


AdaBoostClassifier
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================


XGclassifier
Training set pred
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
----------------------------------------
Test set prediction
accuracy:1.0000
f1score:1.0000
precision:1.0000
recall:1.0000
roc_auc:1.0000
========================================