In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
df = pd.read_csv('cardekho_imputated.csv',index_col=[0])

In [3]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB

In [5]:
df.drop(columns=['car_name','brand'],axis=1,inplace=True)

In [6]:
X= df.drop('selling_price',axis=1)
y=df['selling_price']

In [7]:
X['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
leb = LabelEncoder()
X['model']=leb.fit_transform(X['model'])

In [9]:
numerical_feature =X.select_dtypes(exclude='object').columns
categorical_feature = ['seller_type','fuel_type','transmission_type']

In [10]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
Numeracl_transformer= StandardScaler()
categorical_transformer = OneHotEncoder(drop='first')

preprocess = ColumnTransformer(
    [
        ('oneHotEncoder',categorical_transformer,categorical_feature),
        ('standscler',Numeracl_transformer,numerical_feature)
    ]
)

In [11]:
X =preprocess.fit_transform(X)

In [12]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression ,Ridge,Lasso
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [18]:
def Evel_predict(true,predict):
    r2_scor = r2_score(true,predict)
    mae= mean_absolute_error(true,predict)
    mse= mean_squared_error(true,predict)
    rmse = np.sqrt(mse)
    return r2_scor,mae,rmse

In [27]:
models={
    'linearRegression':LinearRegression(),
    'SVR':SVR(),
    'KNeighborsRegressor':KNeighborsRegressor(),
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'GradientBoostingRegressor':GradientBoostingRegressor(),
    'RandomForestRegressor':RandomForestRegressor(),
    'AdaBoostRegressor':AdaBoostRegressor()
    }
for i in range(len(list(models))):
    model= list(models.values())[i]
    model.fit(X_train,y_train)
    Y_train_pred =model.predict(X_train)
    Y_test_pred = model.predict(X_test)

    
    r2_scortrain,maetrain,rmsetrain=Evel_predict(y_train,Y_train_pred)
    r2_scortest,maetest,rmsetest=Evel_predict(y_test,Y_test_pred)

    print(list(models.keys())[i])
    print('Train set prediction\n')
    print('r2_score:{:.4f}'.format(r2_scortrain))
    print('mean Absolute Error:{:.4f}'.format(maetrain))
    print('RootMeanSquaredError{:.4f}'.format(rmsetrain))

    print('-'*32)

    print('Test Set Prediction')
    print('r2_score:{:.4f}'.format(r2_scortest))
    print('mean Absolute Error:{:.4f}'.format(maetest))
    print('Root Mean Squared Error:{:.4f}'.format(rmsetest))

    print('='*32)
    print('\n')

linearRegression
Train set prediction

r2_score:0.6220
mean Absolute Error:266675.1076
RootMeanSquaredError552154.2495
--------------------------------
Test Set Prediction
r2_score:0.6525
mean Absolute Error:284283.4460
Root Mean Squared Error:519891.2635
================================


SVR
Train set prediction

r2_score:-0.0537
mean Absolute Error:393323.8367
RootMeanSquaredError921881.6069
--------------------------------
Test Set Prediction
r2_score:-0.0683
mean Absolute Error:421445.2031
Root Mean Squared Error:911526.8939
================================


KNeighborsRegressor
Train set prediction

r2_score:0.8654
mean Absolute Error:90967.3646
RootMeanSquaredError329513.6739
--------------------------------
Test Set Prediction
r2_score:0.8987
mean Absolute Error:116579.3732
Root Mean Squared Error:280676.9784
================================


DecisionTreeRegressor
Train set prediction

r2_score:0.9995
mean Absolute Error:4991.7517
RootMeanSquaredError20644.8585
--------------------------------
Test Set Prediction
r2_score:0.8678
mean Absolute Error:133525.9949
Root Mean Squared Error:320593.9596
================================


GradientBoostingRegressor
Train set prediction

r2_score:0.9509
mean Absolute Error:110635.4519
RootMeanSquaredError199010.3871
--------------------------------
Test Set Prediction
r2_score:0.9089
mean Absolute Error:128349.3620
Root Mean Squared Error:266192.9229
================================


RandomForestRegressor
Train set prediction

r2_score:0.9686
mean Absolute Error:40033.5389
RootMeanSquaredError159103.4616
--------------------------------
Test Set Prediction
r2_score:0.9242
mean Absolute Error:105255.6912
Root Mean Squared Error:242867.4940
================================


AdaBoostRegressor
Train set prediction

r2_score:0.7714
mean Absolute Error:327427.2953
RootMeanSquaredError429401.0665
--------------------------------
Test Set Prediction
r2_score:0.6676
mean Absolute Error:350641.6288
Root Mean Squared Error:508462.0616
================================